# Generated by Django 5.2.6 on 2026-01-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='verificationcode',
            name='uniq_active_user_channel_purpose',
        ),
    ]
