# Generated by Django 5.2.6 on 2026-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_verificationcode_uniq_active_user_channel_purpose'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='verificationcode',
            constraint=models.UniqueConstraint(condition=models.Q(('consumed_at__isnull', True)), fields=('user', 'channel', 'purpose'), name='uniq_active_user_channel_purpose'),
        ),
    ]
