# Generated by Django 5.1 on 2025-08-31 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='bounce_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='bounced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='bounced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='complained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='complained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='complaint_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='consent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='consent_source',
            field=models.CharField(blank=True, help_text='e.g. form path or campaign', max_length=255),
        ),
        migrations.AddField(
            model_name='subscription',
            name='consent_text',
            field=models.TextField(blank=True, help_text='Snapshot of the consent wording shown to user'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='consent_user_agent',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='email_opt_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gdpr_erased_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='lawful_basis',
            field=models.CharField(choices=[('consent', 'Consent'), ('contract', 'Contract'), ('legit_interest', 'Legitimate Interest')], default='consent', max_length=32),
        ),
        migrations.CreateModel(
            name='SubscriptionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('subscribe', 'Subscribe'), ('unsubscribe', 'Unsubscribe'), ('consent', 'Consent'), ('update_prefs', 'Update Preferences'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('erase', 'Erase (GDPR)')], max_length=32)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='news.subscription')),
            ],
            options={
                'ordering': ['-at'],
            },
        ),
    ]
