# Generated by Django 5.1 on 2025-09-02 08:48

import secrets
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscription_bounce_reason_subscription_bounced_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='Issue',
        ),
        migrations.RenameModel(
            old_name='Submission',
            new_name='Mailing',
        ),
        migrations.AlterModelOptions(
            name='subscription',
            options={'ordering': ['-created'], 'verbose_name': 'subscription', 'verbose_name_plural': 'subscriptions'},
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_code',
            field=models.CharField(default=secrets.token_urlsafe, max_length=40, unique=True),
        ),
    ]
