# Generated by Django 5.1 on 2025-09-02 13:43

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_message_issue_rename_submission_mailing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='public',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not users can self-subscribe.', verbose_name='public'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='activation_code',
            field=models.CharField(default=news.models.generate_activation_code, max_length=40, unique=True),
        ),
    ]
