# Generated by Django 5.1 on 2025-09-12 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsletter_public_alter_subscription_activation_code'),
    ]

    operations = [
        # migrations.RemoveConstraint(
        #     model_name='subscription',
        #     name='sub_user_xor_email_not_both',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='subscription',
        #     name='sub_user_or_email_required',
        # ),
        migrations.RemoveConstraint(
            model_name='subscription',
            name='uniq_newsletter_user',
        ),
    ]
