# Generated by Django 5.1 on 2025-09-12 18:29

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_remove_subscription_sub_user_xor_email_not_both_and_more'),
        ('web', '0007_remove_commstemplate_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Updated Date')),
                ('provider_event_id', models.CharField(max_length=255, unique=True)),
                ('event', models.CharField(choices=[('accepted', 'accepted'), ('rejected', 'rejected'), ('delivered', 'delivered'), ('failed', 'failed'), ('opened', 'opened'), ('clicked', 'clicked'), ('unsubscribed', 'unsubscribed'), ('complained', 'complained'), ('stored', 'stored')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('recipient', models.EmailField(max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('geo', models.JSONField(blank=True, default=dict)),
                ('url', models.URLField(blank=True)),
                ('delivery_status', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField()),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DirectEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created Date')),
                ('updated', models.DateTimeField(blank=True, db_index=True, editable=False, null=True, verbose_name='Updated Date')),
                ('to_email', models.EmailField(db_index=True, max_length=254)),
                ('event_ref', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('body_html', models.TextField(blank=True)),
                ('body_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'queued'), ('sending', 'sending'), ('sent', 'sent'), ('error', 'error')], default='queued', max_length=12)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='delivery',
            options={},
        ),
        # migrations.RemoveConstraint(
        #     model_name='subscription',
        #     name='sub_user_xor_email_not_both',
        # ),
        # migrations.RemoveConstraint(
        #     model_name='subscription',
        #     name='sub_user_or_email_required',
        # ),
        migrations.RenameField(
            model_name='delivery',
            old_name='timestamp',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='event',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='submission',
        ),
        migrations.AddField(
            model_name='article',
            name='template_type',
            field=models.CharField(choices=[('N', 'Newsletter'), ('E', 'Email')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='delivery',
            name='campaigns',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='delivery',
            name='click_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='complained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='delivery',
            name='failure_severity',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_clicked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_event',
            field=models.CharField(blank=True, choices=[('queued', 'Queued'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('rejected', 'Rejected'), ('stored', 'Stored')], max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_event_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='last_opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='news.mailing'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='delivery',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider_message_size',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Bytes', validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='delivery',
            name='provider_storage_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='queued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='raw_delivery_status',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='delivery',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='smtp_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='smtp_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='state',
            field=models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('clicked', 'Clicked'), ('failed', 'Failed'), ('complained', 'Complained'), ('unsubscribed', 'Unsubscribed'), ('rejected', 'Rejected'), ('stored', 'Stored')], default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='stored_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='delivery',
            name='unsubscribed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='user_variables',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='delivery',
            name='webhook_signature_sig',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='webhook_signature_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='delivery',
            name='webhook_signature_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='webhook_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='news.delivery'),
        ),
        migrations.AddField(
            model_name='deliveryevent',
            name='updator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directemail',
            name='article',
            field=models.ForeignKey(blank=True, limit_choices_to={'template_type': 'E'}, null=True, on_delete=django.db.models.deletion.PROTECT, to='news.article'),
        ),
        migrations.AddField(
            model_name='directemail',
            name='competitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.competitor'),
        ),
        migrations.AddField(
            model_name='directemail',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directemail',
            name='delivery',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='direct_email', to='news.delivery'),
        ),
        migrations.AddField(
            model_name='directemail',
            name='entries',
            field=models.ManyToManyField(to='web.entry'),
        ),
        migrations.AddField(
            model_name='directemail',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.event'),
        ),
        migrations.AddField(
            model_name='directemail',
            name='eventrole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.eventrole'),
        ),
        migrations.AddField(
            model_name='directemail',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='Recipient user, if linked to an account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directemail',
            name='sender',
            field=models.ForeignKey(help_text='The staff user who initiated this email', on_delete=django.db.models.deletion.PROTECT, related_name='emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directemail',
            name='updator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_updator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='directemail',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='delivery',
            name='direct_mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_deliveries', to='news.directemail'),
        ),
    ]
