# Generated by Django 5.1 on 2025-09-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_deliveryevent_directemail_alter_delivery_options_and_more'),
    ]

    operations = [

        migrations.AddField(
            model_name='newsletter',
            name='about',
            field=models.TextField(blank=True, help_text='Short description shown on subscribe page', null=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='public',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether or not users can self-subscribe.'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='visible',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
