# Generated by Django 5.1 on 2025-09-19 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_remove_subscription_sub_user_xor_email_not_both_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailing',
            old_name='message',
            new_name='issue',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='status',
            field=models.CharField(choices=[('0', 'Inactive'), ('1', 'Queued'), ('2', 'Sending'), ('3', 'Sent'), ('9', 'Error')], default='0', max_length=1),
        ),
    ]
