# Generated by Django 5.1 on 2025-09-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_rename_message_mailing_issue_alter_mailing_status'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='subscription',
        #     name='email_opt_in',
        # ),
        migrations.AddField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(db_index=True, default=True, help_text='True when consent is present and the subscription is deliverable.'),
        ),
        migrations.AlterField(
            model_name='subscriptionevent',
            name='event',
            field=models.CharField(choices=[('subscribe', 'Subscribe'), ('unsubscribe', 'Unsubscribe'), ('consent', 'Consent'), ('subscribe_consent', 'Subscribe and Consent'), ('unsubscribe_consent', 'Subscribe and Consent'), ('update_prefs', 'Update Preferences'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('erase', 'Erase (GDPR)')], max_length=32),
        ),
    ]
