# Generated by Django 5.1 on 2025-09-20 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_remove_subscription_email_opt_in_subscription_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='directemail',
            name='sender',
            field=models.ForeignKey(blank=True, help_text='The staff user who initiated this email', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.BooleanField(db_index=True, default=False, help_text='True when consent is present and the subscription is deliverable.'),
        ),
        migrations.AlterField(
            model_name='subscriptionevent',
            name='event',
            field=models.CharField(choices=[('subscribe', 'Subscribe'), ('unsubscribe', 'Unsubscribe'), ('consent', 'Consent'), ('subscribe_consent', 'Subscribe and Consent'), ('update_prefs', 'Update Preferences'), ('bounce', 'Bounce'), ('complaint', 'Complaint'), ('erase', 'Erase (GDPR)'), ('email_sent', 'Email Sent')], max_length=32),
        ),
    ]
