# Generated by Django 5.1 on 2025-09-23 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_directemail_sender_alter_subscription_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'ordering': ['-created']},
        ),
        migrations.AlterModelOptions(
            name='directemail',
            options={'ordering': ['-created']},
        ),

        migrations.RemoveField(
            model_name='delivery',
            name='webhook_signature_sig',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='webhook_signature_token',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='webhook_signature_ts',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='webhook_verified',
        ),
        migrations.RemoveField(
            model_name='directemail',
            name='delivery',
        ),
        migrations.AddField(
            model_name='delivery',
            name='esp_name',
            field=models.CharField(db_index=True, default='mailgun', help_text="Which ESP handled the send (e.g., 'mailgun').", max_length=20),
        ),
        migrations.AddField(
            model_name='delivery',
            name='message_id',
            field=models.CharField(blank=True, help_text='Provider message id returned by Anymail.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='directemail',
            name='from_email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='directemail',
            name='article',
            field=models.ForeignKey(blank=True, limit_choices_to={'template_type': 'E'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='direct_emails', to='news.article'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['state', 'last_event_at'], name='news_delive_state_1ab992_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['email', 'state'], name='news_delive_email_71da80_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery',
            index=models.Index(fields=['esp_name'], name='news_delive_esp_nam_134c26_idx'),
        ),
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('esp_name', 'message_id'), name='uniq_delivery_esp_message'),
        ),
    ]
