# Generated by Django 5.1 on 2025-09-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_alter_delivery_options_alter_directemail_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directemail',
            name='template',
            field=models.CharField(blank=True, help_text='Optional template name that appears in templates/email directory to render from', max_length=50, null=True),
        ),
    ]
