# Generated by Django 5.1 on 2025-09-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_directemail_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directemail',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('error', 'Error')], default='draft', max_length=7),
        ),
    ]
