# Generated by Django 5.2.6 on 2026-01-17 12:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ref', models.CharField(help_text='Unique reference for the event', max_length=5, unique=True)),
                ('event_group', models.JSONField(blank=True, default=list, help_text='List of event refs in this group')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('name', models.CharField(max_length=60, verbose_name='Name')),
                ('email', models.EmailField(blank=True, db_index=True, help_text='Email used for notifications for this event only', max_length=254, null=True, verbose_name='email address')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_person', to='users.person')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_role', to='users.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_user', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_ref', models.CharField(blank=True, db_index=True, max_length=5, null=True)),
                ('ref', models.CharField(blank=True, max_length=9, null=True, unique=True)),
                ('entryid', models.CharField(blank=True, db_index=True, help_text='Organiser assigned number or reference', max_length=32, null=True)),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.competition')),
                ('competitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entry_competitor', to='web.competitor')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.event')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='web.event'),
        ),
        migrations.CreateModel(
            name='EventRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_type', models.CharField(choices=[('O', 'Organiser'), ('J', 'Judge'), ('L', 'Leader'), ('K', 'Trainee Judge'), ('B', 'Scorer'), ('S', 'Scorer Pro'), ('E', 'Steward'), ('W', 'Writer'), ('G', 'Dogsbody'), ('R', 'Competitor')], max_length=1)),
                ('name', models.CharField(max_length=60)),
                ('role_ref', models.CharField(blank=True, db_index=True, max_length=7, null=True)),
                ('email', models.EmailField(blank=True, help_text='Email used for notifications for this event only - will be removed after event', max_length=254, null=True, verbose_name='email address')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.role')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
