# Generated by Django 4.2.24 on 2025-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skorie_news', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='delivery',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('esp_name', 'message_id'), name='uniq_delivery_esp_message'),
        ),
        migrations.AddConstraint(
            model_name='subscription',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False)), fields=('newsletter', 'email'), name='uniq_newsletter_email'),
        ),
    ]
