# Generated by Django 4.2.24 on 2025-11-14 16:16

from django.db import migrations, models
import skorie_news.models
import skorie_news.skorie_storage.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('skorie_news', '0002_delivery_uniq_delivery_esp_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=skorie_news.skorie_storage.storage_backends.HetznerPrivateStorage, upload_to='newsletter/articles/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=skorie_news.skorie_storage.storage_backends.HetznerPrivateStorage, upload_to=skorie_news.models.attachment_upload_to, verbose_name='attachment'),
        ),
        # migrations.AddConstraint(
        #     model_name='delivery',
        #     constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('esp_name', 'message_id'), name='uniq_delivery_esp_message'),
        # ),
    ]
