# Generated by Django 4.2.26 on 2025-11-28 18:48

from django.db import migrations, models
import django.db.models.deletion
import skorie_news.models
import skorie_news.skorie_storage.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('skorie_news', '0003_alter_article_image_alter_attachment_file_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ['-created'], 'verbose_name': 'mailing', 'verbose_name_plural': 'mailings'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='reply to e-mail'),
        ),

        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=skorie_news.skorie_storage.storage_backends.HetznerPublicStorage(), upload_to=skorie_news.models.Article.image_location),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(storage=skorie_news.skorie_storage.storage_backends.HetznerPublicStorage(), upload_to=skorie_news.models.attachment_upload_to, verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='newsletter',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='skorie_news.newsletter'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='mailings', to='skorie_news.subscription'),
        ),
        # migrations.AddConstraint(
        #     model_name='delivery',
        #     constraint=models.UniqueConstraint(condition=models.Q(('message_id__isnull', False)), fields=('esp_name', 'message_id'), name='uniq_delivery_esp_message'),
        # ),
    ]
