# Generated by Django 4.2.24 on 2025-12-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skorie_news', '0004_alter_mailing_options_newsletter_reply_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image_position',
            field=models.CharField(choices=[('above', 'Above text'), ('below', 'Below text'), ('left', 'Left of text'), ('right', 'Right of text'), ('only_image', 'Only image')], default='above', max_length=10),
        ),

    ]
