# Generated by Django 4.2.24 on 2026-01-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skorie_news', '0005_alter_article_image_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='message_id',
            field=models.CharField(blank=True, help_text='Provider message id returned by Anymail.', max_length=255, null=True),
        ),
    ]
